sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t deb-sam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deb-sam/docker-react npm run test
